#查询本地点源最后记录
SELECT T1.T_STATION_ID,max(t3.data)
FROM T_STATION_INFO T1
INNER JOIN T_ENT_INFO T2 ON(T1.T_ENT_ID=T2.T_ENT_ID AND T2.NEED_DATA='1')
LEFT JOIN T_ENT_SHURU T3 ON(T1.T_STATION_ID=T3.T_STATION_ID AND T3.data>=TRUNC(SYSDATE,'YYYY'))
group by T1.T_STATION_ID

#按月查询记录数
SELECT T1.T_STATION_ID,TRUNC(T3.DATA,'MM'),COUNT(1)
FROM T_STATION_INFO T1
INNER JOIN T_ENT_INFO T2 ON(T1.T_ENT_ID=T2.T_ENT_ID AND T2.NEED_DATA='1')
LEFT JOIN T_ENT_SHURU T3 ON(T1.T_STATION_ID=T3.T_STATION_ID AND T3.data>=TRUNC(SYSDATE,'YYYY'))
group by T1.T_STATION_ID,TRUNC(T3.DATA,'MM')

#查询中间库
select * from ps_gas_hour_data t where t.outputcode='33330206000052'
and t.monitortime>=to_date('2018/2/1','yyyy/mm/dd')
and t.monitortime<to_date('2018/3/1','yyyy/mm/dd')
